# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: yarn install
      run: |
        cd buildAndReleaseTask
        ls
        yarn 
    
    - name: typescript compile
      run: |
        cd buildAndReleaseTask
        tsc
      
    - name: upload task
      run: |
        sudo npm install -g tfx-cli
        tfx extension publish -t aue7z7akzudsh44zrfzbrx3atfrf7znj5kqar3uce2syc2quam4a -u https://gabrielggff25.visualstudio.com/DefaultCollection/ --task-path .
